/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

/**
 *
 * @author Nguyễn Xuân Nam
 */
public class panel_QuanLyTaiLieu extends javax.swing.JPanel {

    /**
     * Creates new form panel_QuanLyTaiLieu
     */
    public panel_QuanLyTaiLieu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab_TaiLieu = new javax.swing.JTabbedPane();
        pnl_PhieuDatPhong = new javax.swing.JPanel();
        pnl_TimKiemPhieu = new javax.swing.JPanel();
        lbl_Tab1SoDienThoai = new javax.swing.JLabel();
        lbl_ThoiGian = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        txt_Tab1SoDienThoai = new javax.swing.JTextField();
        lbl_MaPhieu = new javax.swing.JLabel();
        lbl_Phong = new javax.swing.JLabel();
        txt_MaPhieu = new javax.swing.JTextField();
        txt_Phong = new javax.swing.JTextField();
        btn_Tab1TimKiem = new javax.swing.JButton();
        btn_Tab1LamMoi = new javax.swing.JButton();
        pnl_DSPhieuDat = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_DSPhieuDat = new javax.swing.JTable();
        pnl_HoaDon = new javax.swing.JPanel();
        pnl_TimKiemHoaDon = new javax.swing.JPanel();
        lbl_Tab2SoDienThoai = new javax.swing.JLabel();
        txt_Tab2SoDienThoai = new javax.swing.JTextField();
        lbl_NgayLap = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        lbl_DenNgay = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        btn_Tab2TimKiem = new javax.swing.JButton();
        lbl_MaNhanVien = new javax.swing.JLabel();
        txt_MaNhanVien = new javax.swing.JTextField();
        lbl_TongHoaDon = new javax.swing.JLabel();
        txt_TongHoaDonT = new javax.swing.JTextField();
        lbl_Den = new javax.swing.JLabel();
        txt_TongHoaDonS = new javax.swing.JTextField();
        btn_Tab2LamMoi = new javax.swing.JButton();
        pnl_DSHoaDon = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_DSHoaDon = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pnl_PhieuDatPhong.setLayout(new java.awt.BorderLayout());

        pnl_TimKiemPhieu.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm phiếu đặt"));

        lbl_Tab1SoDienThoai.setText("Số điện thoại");

        lbl_ThoiGian.setText("Thời gian");

        jFormattedTextField1.setText("jFormattedTextField1");

        txt_Tab1SoDienThoai.setText("jTextField1");

        lbl_MaPhieu.setText("Mã phiếu");

        lbl_Phong.setText("Phòng");

        txt_MaPhieu.setText("jTextField2");
        txt_MaPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaPhieuActionPerformed(evt);
            }
        });

        txt_Phong.setText("jTextField3");
        txt_Phong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PhongActionPerformed(evt);
            }
        });

        btn_Tab1TimKiem.setText("Tìm kiếm");
        btn_Tab1TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Tab1TimKiemActionPerformed(evt);
            }
        });

        btn_Tab1LamMoi.setText("Làm mới");

        javax.swing.GroupLayout pnl_TimKiemPhieuLayout = new javax.swing.GroupLayout(pnl_TimKiemPhieu);
        pnl_TimKiemPhieu.setLayout(pnl_TimKiemPhieuLayout);
        pnl_TimKiemPhieuLayout.setHorizontalGroup(
            pnl_TimKiemPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TimKiemPhieuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnl_TimKiemPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_ThoiGian)
                    .addComponent(lbl_Tab1SoDienThoai))
                .addGap(31, 31, 31)
                .addGroup(pnl_TimKiemPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Tab1SoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pnl_TimKiemPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_TimKiemPhieuLayout.createSequentialGroup()
                        .addComponent(lbl_Phong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_Phong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_TimKiemPhieuLayout.createSequentialGroup()
                        .addComponent(lbl_MaPhieu)
                        .addGap(47, 47, 47)
                        .addComponent(txt_MaPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 598, Short.MAX_VALUE)
                .addGroup(pnl_TimKiemPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Tab1TimKiem, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Tab1LamMoi, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnl_TimKiemPhieuLayout.setVerticalGroup(
            pnl_TimKiemPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TimKiemPhieuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnl_TimKiemPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Tab1SoDienThoai)
                    .addComponent(txt_Tab1SoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_MaPhieu)
                    .addComponent(txt_MaPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Tab1TimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_TimKiemPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ThoiGian)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Phong)
                    .addComponent(txt_Phong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Tab1LamMoi))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnl_PhieuDatPhong.add(pnl_TimKiemPhieu, java.awt.BorderLayout.NORTH);

        pnl_DSPhieuDat.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách phiếu đặt"));

        tbl_DSPhieuDat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_DSPhieuDat);

        javax.swing.GroupLayout pnl_DSPhieuDatLayout = new javax.swing.GroupLayout(pnl_DSPhieuDat);
        pnl_DSPhieuDat.setLayout(pnl_DSPhieuDatLayout);
        pnl_DSPhieuDatLayout.setHorizontalGroup(
            pnl_DSPhieuDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_DSPhieuDatLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1112, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_DSPhieuDatLayout.setVerticalGroup(
            pnl_DSPhieuDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_DSPhieuDatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_PhieuDatPhong.add(pnl_DSPhieuDat, java.awt.BorderLayout.CENTER);

        tab_TaiLieu.addTab("Phiếu đặt phòng", pnl_PhieuDatPhong);

        pnl_HoaDon.setLayout(new java.awt.BorderLayout());

        pnl_TimKiemHoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm hóa đơn"));
        pnl_TimKiemHoaDon.setLayout(new java.awt.GridLayout(2, 0));

        lbl_Tab2SoDienThoai.setText("Số điện thoại");
        pnl_TimKiemHoaDon.add(lbl_Tab2SoDienThoai);
        pnl_TimKiemHoaDon.add(txt_Tab2SoDienThoai);

        lbl_NgayLap.setText("Ngày lập:");
        pnl_TimKiemHoaDon.add(lbl_NgayLap);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        pnl_TimKiemHoaDon.add(jTextField5);

        lbl_DenNgay.setText("đến ngày:");
        pnl_TimKiemHoaDon.add(lbl_DenNgay);
        pnl_TimKiemHoaDon.add(jTextField3);

        btn_Tab2TimKiem.setText("Tìm kiếm");
        btn_Tab2TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Tab2TimKiemActionPerformed(evt);
            }
        });
        pnl_TimKiemHoaDon.add(btn_Tab2TimKiem);

        lbl_MaNhanVien.setText("Mã nhân viên");
        pnl_TimKiemHoaDon.add(lbl_MaNhanVien);

        txt_MaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaNhanVienActionPerformed(evt);
            }
        });
        pnl_TimKiemHoaDon.add(txt_MaNhanVien);

        lbl_TongHoaDon.setText("Tổng hóa đơn");
        pnl_TimKiemHoaDon.add(lbl_TongHoaDon);
        pnl_TimKiemHoaDon.add(txt_TongHoaDonT);

        lbl_Den.setText("đến");
        pnl_TimKiemHoaDon.add(lbl_Den);
        pnl_TimKiemHoaDon.add(txt_TongHoaDonS);

        btn_Tab2LamMoi.setText("Làm mới");
        pnl_TimKiemHoaDon.add(btn_Tab2LamMoi);

        pnl_HoaDon.add(pnl_TimKiemHoaDon, java.awt.BorderLayout.NORTH);

        pnl_DSHoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách hóa đơn"));
        pnl_DSHoaDon.setLayout(new java.awt.BorderLayout());

        tbl_DSHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_DSHoaDon);

        pnl_DSHoaDon.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pnl_HoaDon.add(pnl_DSHoaDon, java.awt.BorderLayout.CENTER);

        tab_TaiLieu.addTab("Hóa đơn", pnl_HoaDon);

        add(tab_TaiLieu, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Tab1TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Tab1TimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Tab1TimKiemActionPerformed

    private void txt_MaPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaPhieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaPhieuActionPerformed

    private void txt_PhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PhongActionPerformed

    private void btn_Tab2TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Tab2TimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Tab2TimKiemActionPerformed

    private void txt_MaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaNhanVienActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Tab1LamMoi;
    private javax.swing.JButton btn_Tab1TimKiem;
    private javax.swing.JButton btn_Tab2LamMoi;
    private javax.swing.JButton btn_Tab2TimKiem;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lbl_Den;
    private javax.swing.JLabel lbl_DenNgay;
    private javax.swing.JLabel lbl_MaNhanVien;
    private javax.swing.JLabel lbl_MaPhieu;
    private javax.swing.JLabel lbl_NgayLap;
    private javax.swing.JLabel lbl_Phong;
    private javax.swing.JLabel lbl_Tab1SoDienThoai;
    private javax.swing.JLabel lbl_Tab2SoDienThoai;
    private javax.swing.JLabel lbl_ThoiGian;
    private javax.swing.JLabel lbl_TongHoaDon;
    private javax.swing.JPanel pnl_DSHoaDon;
    private javax.swing.JPanel pnl_DSPhieuDat;
    private javax.swing.JPanel pnl_HoaDon;
    private javax.swing.JPanel pnl_PhieuDatPhong;
    private javax.swing.JPanel pnl_TimKiemHoaDon;
    private javax.swing.JPanel pnl_TimKiemPhieu;
    private javax.swing.JTabbedPane tab_TaiLieu;
    private javax.swing.JTable tbl_DSHoaDon;
    private javax.swing.JTable tbl_DSPhieuDat;
    private javax.swing.JTextField txt_MaNhanVien;
    private javax.swing.JTextField txt_MaPhieu;
    private javax.swing.JTextField txt_Phong;
    private javax.swing.JTextField txt_Tab1SoDienThoai;
    private javax.swing.JTextField txt_Tab2SoDienThoai;
    private javax.swing.JTextField txt_TongHoaDonS;
    private javax.swing.JTextField txt_TongHoaDonT;
    // End of variables declaration//GEN-END:variables
}
