/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.awt.Label;
import javax.swing.JLabel;

/**
 *
 * @author nxnam
 */
public class panel_ThongKe extends javax.swing.JPanel {

    /**
     * Creates new form Panel_ThongKe
     */
    private JLabel myNewLabel;
    
    
    public panel_ThongKe() {
        initComponents();
         // Tạo một nhãn mới
        myNewLabel = new JLabel("Đây là nhãn mới");

        // Đặt vị trí và kích thước của nhãn
        myNewLabel.setBounds(50, 50, 150, 30);

        // Thêm nhãn vào panel
        this.add(myNewLabel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_tren = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pnl_DonHang = new javax.swing.JPanel();
        lbl_ImgDonHang = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_DonHang = new javax.swing.JLabel();
        lbl_SoLuongDon = new javax.swing.JLabel();
        pnl_DoanhThu = new javax.swing.JPanel();
        lbl_DoanhThu = new javax.swing.JLabel();
        lbl_SoLuongDoanhThu = new javax.swing.JLabel();
        lbl_ImgDoanhThu = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnl_PhongDung = new javax.swing.JPanel();
        lbl_PhongDung = new javax.swing.JLabel();
        lbl_SoPhongDung = new javax.swing.JLabel();
        lbl_ImgPhongDung = new javax.swing.JLabel();
        pnl_PhongCho = new javax.swing.JPanel();
        lbl_PhongCho = new javax.swing.JLabel();
        lbl_SoPhongCho = new javax.swing.JLabel();
        lbl_ImgPhongCho = new javax.swing.JLabel();
        pnl_giua = new javax.swing.JPanel();
        pnl_duoi = new javax.swing.JPanel();

        pnl_tren.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        pnl_DonHang.setLayout(new java.awt.BorderLayout());

        lbl_ImgDonHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilities/icon/microphone.png"))); // NOI18N
        lbl_ImgDonHang.setText("  ");
        pnl_DonHang.add(lbl_ImgDonHang, java.awt.BorderLayout.WEST);

        jPanel3.setLayout(new java.awt.GridLayout(2, 1, 0, 8));

        lbl_DonHang.setText("Đơn hàng");
        jPanel3.add(lbl_DonHang);

        lbl_SoLuongDon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_SoLuongDon.setText("3");
        jPanel3.add(lbl_SoLuongDon);

        pnl_DonHang.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.add(pnl_DonHang, java.awt.BorderLayout.WEST);

        lbl_DoanhThu.setText("lbl_Doanhthu");

        lbl_SoLuongDoanhThu.setText("lbl_SoLuongDoanhThu");

        lbl_ImgDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilities/icon/verified-account.png"))); // NOI18N
        lbl_ImgDoanhThu.setText("  ");

        javax.swing.GroupLayout pnl_DoanhThuLayout = new javax.swing.GroupLayout(pnl_DoanhThu);
        pnl_DoanhThu.setLayout(pnl_DoanhThuLayout);
        pnl_DoanhThuLayout.setHorizontalGroup(
            pnl_DoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_DoanhThuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_ImgDoanhThu)
                .addGap(0, 0, 0)
                .addGroup(pnl_DoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_DoanhThu)
                    .addComponent(lbl_SoLuongDoanhThu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_DoanhThuLayout.setVerticalGroup(
            pnl_DoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_DoanhThuLayout.createSequentialGroup()
                .addGroup(pnl_DoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_DoanhThuLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lbl_DoanhThu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_SoLuongDoanhThu))
                    .addGroup(pnl_DoanhThuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_ImgDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(pnl_DoanhThu, java.awt.BorderLayout.EAST);

        pnl_tren.add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setLayout(new java.awt.BorderLayout());

        lbl_PhongDung.setText("jLabel1");

        lbl_SoPhongDung.setText("jLabel2");

        lbl_ImgPhongDung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilities/icon/home.png"))); // NOI18N
        lbl_ImgPhongDung.setText("  ");

        javax.swing.GroupLayout pnl_PhongDungLayout = new javax.swing.GroupLayout(pnl_PhongDung);
        pnl_PhongDung.setLayout(pnl_PhongDungLayout);
        pnl_PhongDungLayout.setHorizontalGroup(
            pnl_PhongDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_PhongDungLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_ImgPhongDung)
                .addGap(47, 47, 47)
                .addGroup(pnl_PhongDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_PhongDung, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_SoPhongDung, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnl_PhongDungLayout.setVerticalGroup(
            pnl_PhongDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_PhongDungLayout.createSequentialGroup()
                .addGroup(pnl_PhongDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_PhongDungLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lbl_PhongDung)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_SoPhongDung))
                    .addGroup(pnl_PhongDungLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_ImgPhongDung, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.add(pnl_PhongDung, java.awt.BorderLayout.WEST);

        lbl_PhongCho.setText("jLabel1");

        lbl_SoPhongCho.setText("jLabel2");

        lbl_ImgPhongCho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilities/icon/microphone.png"))); // NOI18N
        lbl_ImgPhongCho.setText("  ");

        javax.swing.GroupLayout pnl_PhongChoLayout = new javax.swing.GroupLayout(pnl_PhongCho);
        pnl_PhongCho.setLayout(pnl_PhongChoLayout);
        pnl_PhongChoLayout.setHorizontalGroup(
            pnl_PhongChoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_PhongChoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_ImgPhongCho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_PhongChoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_PhongCho, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_SoPhongCho, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnl_PhongChoLayout.setVerticalGroup(
            pnl_PhongChoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_PhongChoLayout.createSequentialGroup()
                .addGroup(pnl_PhongChoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_PhongChoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lbl_PhongCho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_SoPhongCho))
                    .addGroup(pnl_PhongChoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_ImgPhongCho, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(pnl_PhongCho, java.awt.BorderLayout.EAST);

        pnl_tren.add(jPanel2, java.awt.BorderLayout.EAST);

        javax.swing.GroupLayout pnl_giuaLayout = new javax.swing.GroupLayout(pnl_giua);
        pnl_giua.setLayout(pnl_giuaLayout);
        pnl_giuaLayout.setHorizontalGroup(
            pnl_giuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnl_giuaLayout.setVerticalGroup(
            pnl_giuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnl_duoiLayout = new javax.swing.GroupLayout(pnl_duoi);
        pnl_duoi.setLayout(pnl_duoiLayout);
        pnl_duoiLayout.setHorizontalGroup(
            pnl_duoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnl_duoiLayout.setVerticalGroup(
            pnl_duoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_tren, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnl_giua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_duoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_tren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_giua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(pnl_duoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_DoanhThu;
    private javax.swing.JLabel lbl_DonHang;
    private javax.swing.JLabel lbl_ImgDoanhThu;
    private javax.swing.JLabel lbl_ImgDonHang;
    private javax.swing.JLabel lbl_ImgPhongCho;
    private javax.swing.JLabel lbl_ImgPhongDung;
    private javax.swing.JLabel lbl_PhongCho;
    private javax.swing.JLabel lbl_PhongDung;
    private javax.swing.JLabel lbl_SoLuongDoanhThu;
    private javax.swing.JLabel lbl_SoLuongDon;
    private javax.swing.JLabel lbl_SoPhongCho;
    private javax.swing.JLabel lbl_SoPhongDung;
    private javax.swing.JPanel pnl_DoanhThu;
    private javax.swing.JPanel pnl_DonHang;
    private javax.swing.JPanel pnl_DonHang1;
    private javax.swing.JPanel pnl_DonHang2;
    private javax.swing.JPanel pnl_DonHang3;
    private javax.swing.JPanel pnl_PhongCho;
    private javax.swing.JPanel pnl_PhongDung;
    private javax.swing.JPanel pnl_duoi;
    private javax.swing.JPanel pnl_giua;
    private javax.swing.JPanel pnl_tren;
    // End of variables declaration//GEN-END:variables
}
