/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

/**
 *
 * @author Nguyễn Xuân Nam
 */
public class pnl_ThanhToan extends javax.swing.JPanel {

    /**
     * Creates new form pnl_ThanhToan
     */
    public pnl_ThanhToan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Trai = new javax.swing.JPanel();
        pnl_DSPhong = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_DSPhong = new javax.swing.JTable();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        pnl_DSDichVu = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_DSDichVu = new javax.swing.JTable();
        pnl_Phai = new javax.swing.JPanel();
        pnl_TienThanhToan = new javax.swing.JPanel();
        lbl_TienPhong = new javax.swing.JLabel();
        lbl_TienDichVu = new javax.swing.JLabel();
        lbl_TongTien = new javax.swing.JLabel();
        lbl_ChietKhau = new javax.swing.JLabel();
        lbl_Thue = new javax.swing.JLabel();
        lbl_TienThanhToan = new javax.swing.JLabel();
        btn_InPhieu = new javax.swing.JButton();
        txt_TongTien = new javax.swing.JTextField();
        txt_TienPhong = new javax.swing.JTextField();
        txt_TienDichVu = new javax.swing.JTextField();
        txt_TienThanhToan = new javax.swing.JTextField();
        txt_ChietKhau = new javax.swing.JTextField();
        txt_Thue = new javax.swing.JTextField();
        pnl_ThongTinKhachHang = new javax.swing.JPanel();
        lbl_SoDienThoai = new javax.swing.JLabel();
        lbl_TenKhachHang = new javax.swing.JLabel();
        lbl_HangThanhVien = new javax.swing.JLabel();
        txt_SoDienThoai = new javax.swing.JTextField();
        txt_TenKhachHang = new javax.swing.JTextField();
        txt_HangThanhVien = new javax.swing.JTextField();
        pnl_ThuTien = new javax.swing.JPanel();
        lbl_TienNhan = new javax.swing.JLabel();
        lbl_TienThua = new javax.swing.JLabel();
        txt_TienNhan = new javax.swing.JTextField();
        txt_TienThua = new javax.swing.JTextField();
        rad_XuatHoaDon = new javax.swing.JRadioButton();
        btn_ThanhToan = new javax.swing.JButton();
        pnl_Tren = new javax.swing.JPanel();
        lbl_TieuDe = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        pnl_Trai.setLayout(new java.awt.BorderLayout());

        pnl_DSPhong.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách phòng hát", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        pnl_DSPhong.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 160));

        tbl_DSPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_DSPhong.setPreferredSize(new java.awt.Dimension(300, 40));
        jScrollPane1.setViewportView(tbl_DSPhong);

        pnl_DSPhong.add(jScrollPane1, java.awt.BorderLayout.CENTER);
        pnl_DSPhong.add(filler2, java.awt.BorderLayout.PAGE_END);

        pnl_Trai.add(pnl_DSPhong, java.awt.BorderLayout.NORTH);

        pnl_DSDichVu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách dịch vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        pnl_DSDichVu.setLayout(new java.awt.BorderLayout());

        tbl_DSDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_DSDichVu.setMaximumSize(null);
        tbl_DSDichVu.setMinimumSize(null);
        tbl_DSDichVu.setPreferredSize(null);
        jScrollPane2.setViewportView(tbl_DSDichVu);

        pnl_DSDichVu.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pnl_Trai.add(pnl_DSDichVu, java.awt.BorderLayout.CENTER);

        add(pnl_Trai, java.awt.BorderLayout.CENTER);

        pnl_Phai.setLayout(new java.awt.BorderLayout());

        pnl_TienThanhToan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnl_TienThanhToan.setAlignmentX(5.0F);
        pnl_TienThanhToan.setAlignmentY(5.0F);

        lbl_TienPhong.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_TienPhong.setText("Tiền phòng");
        lbl_TienPhong.setPreferredSize(new java.awt.Dimension(10, 10));

        lbl_TienDichVu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_TienDichVu.setText("Tiền dịch vụ");
        lbl_TienDichVu.setPreferredSize(new java.awt.Dimension(10, 10));

        lbl_TongTien.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_TongTien.setText("Tổng tiền");
        lbl_TongTien.setPreferredSize(new java.awt.Dimension(10, 10));

        lbl_ChietKhau.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_ChietKhau.setText("Chiết khấu");
        lbl_ChietKhau.setPreferredSize(new java.awt.Dimension(10, 10));

        lbl_Thue.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_Thue.setText("Thuế VAT(10%)");
        lbl_Thue.setPreferredSize(new java.awt.Dimension(10, 10));

        lbl_TienThanhToan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_TienThanhToan.setText("Thanh toán");
        lbl_TienThanhToan.setPreferredSize(new java.awt.Dimension(10, 10));

        btn_InPhieu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_InPhieu.setText("In phiếu tạm tính");
        btn_InPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InPhieuActionPerformed(evt);
            }
        });

        txt_TienDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TienDichVuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_TienThanhToanLayout = new javax.swing.GroupLayout(pnl_TienThanhToan);
        pnl_TienThanhToan.setLayout(pnl_TienThanhToanLayout);
        pnl_TienThanhToanLayout.setHorizontalGroup(
            pnl_TienThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TienThanhToanLayout.createSequentialGroup()
                .addGroup(pnl_TienThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_TienThanhToanLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(pnl_TienThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_TienThanhToanLayout.createSequentialGroup()
                                .addGroup(pnl_TienThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_TienPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_TienDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_TienThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl_TienThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_TienDichVu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_TienPhong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnl_TienThanhToanLayout.createSequentialGroup()
                                .addGroup(pnl_TienThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_ChietKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_TienThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_Thue, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_TienThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_Thue, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_TienThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ChietKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(6, 6, 6))
                    .addGroup(pnl_TienThanhToanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_InPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnl_TienThanhToanLayout.setVerticalGroup(
            pnl_TienThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TienThanhToanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_TienThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TienPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TienPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(pnl_TienThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TienDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TienDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(pnl_TienThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(pnl_TienThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ChietKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ChietKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(pnl_TienThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_TienThanhToanLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lbl_TienThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_TienThanhToanLayout.createSequentialGroup()
                        .addGroup(pnl_TienThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Thue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Thue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addComponent(txt_TienThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btn_InPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pnl_Phai.add(pnl_TienThanhToan, java.awt.BorderLayout.CENTER);

        pnl_ThongTinKhachHang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        lbl_SoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_SoDienThoai.setText("Số điện thoại");

        lbl_TenKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_TenKhachHang.setText("Tên khách hàng");

        lbl_HangThanhVien.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_HangThanhVien.setText("Hạng thành viên");

        javax.swing.GroupLayout pnl_ThongTinKhachHangLayout = new javax.swing.GroupLayout(pnl_ThongTinKhachHang);
        pnl_ThongTinKhachHang.setLayout(pnl_ThongTinKhachHangLayout);
        pnl_ThongTinKhachHangLayout.setHorizontalGroup(
            pnl_ThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ThongTinKhachHangLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnl_ThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_ThongTinKhachHangLayout.createSequentialGroup()
                        .addComponent(lbl_TenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_TenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_ThongTinKhachHangLayout.createSequentialGroup()
                        .addComponent(lbl_HangThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_HangThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_ThongTinKhachHangLayout.createSequentialGroup()
                        .addComponent(lbl_SoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_SoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnl_ThongTinKhachHangLayout.setVerticalGroup(
            pnl_ThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ThongTinKhachHangLayout.createSequentialGroup()
                .addGroup(pnl_ThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_SoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl_ThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl_ThongTinKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_HangThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_HangThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnl_Phai.add(pnl_ThongTinKhachHang, java.awt.BorderLayout.PAGE_START);

        pnl_ThuTien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_TienNhan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_TienNhan.setText("Tiền nhận");

        lbl_TienThua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_TienThua.setText("Tiền thừa");

        txt_TienNhan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_TienNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TienNhanActionPerformed(evt);
            }
        });

        txt_TienThua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_TienThua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TienThuaActionPerformed(evt);
            }
        });

        rad_XuatHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rad_XuatHoaDon.setLabel("Xuất hóa đơn");
        rad_XuatHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_XuatHoaDonActionPerformed(evt);
            }
        });

        btn_ThanhToan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_ThanhToan.setLabel("Xác nhận thanh toán");
        btn_ThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThanhToanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_ThuTienLayout = new javax.swing.GroupLayout(pnl_ThuTien);
        pnl_ThuTien.setLayout(pnl_ThuTienLayout);
        pnl_ThuTienLayout.setHorizontalGroup(
            pnl_ThuTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ThuTienLayout.createSequentialGroup()
                .addGroup(pnl_ThuTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ThuTienLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btn_ThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_ThuTienLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnl_ThuTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_ThuTienLayout.createSequentialGroup()
                                .addComponent(lbl_TienNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_TienNhan, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                            .addGroup(pnl_ThuTienLayout.createSequentialGroup()
                                .addComponent(rad_XuatHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnl_ThuTienLayout.createSequentialGroup()
                                .addComponent(lbl_TienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_TienThua)))))
                .addContainerGap())
        );
        pnl_ThuTienLayout.setVerticalGroup(
            pnl_ThuTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ThuTienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_ThuTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TienNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_TienNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl_ThuTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_TienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_ThuTienLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_TienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rad_XuatHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnl_Phai.add(pnl_ThuTien, java.awt.BorderLayout.SOUTH);

        add(pnl_Phai, java.awt.BorderLayout.EAST);

        pnl_Tren.setLayout(new java.awt.BorderLayout());

        lbl_TieuDe.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_TieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TieuDe.setText("Tính tiền");
        pnl_Tren.add(lbl_TieuDe, java.awt.BorderLayout.CENTER);

        add(pnl_Tren, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_InPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InPhieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_InPhieuActionPerformed

    private void btn_ThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThanhToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ThanhToanActionPerformed

    private void rad_XuatHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_XuatHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad_XuatHoaDonActionPerformed

    private void txt_TienNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TienNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TienNhanActionPerformed

    private void txt_TienThuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TienThuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TienThuaActionPerformed

    private void txt_TienDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TienDichVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TienDichVuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_InPhieu;
    private javax.swing.JButton btn_ThanhToan;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_ChietKhau;
    private javax.swing.JLabel lbl_HangThanhVien;
    private javax.swing.JLabel lbl_SoDienThoai;
    private javax.swing.JLabel lbl_TenKhachHang;
    private javax.swing.JLabel lbl_Thue;
    private javax.swing.JLabel lbl_TienDichVu;
    private javax.swing.JLabel lbl_TienNhan;
    private javax.swing.JLabel lbl_TienPhong;
    private javax.swing.JLabel lbl_TienThanhToan;
    private javax.swing.JLabel lbl_TienThua;
    private javax.swing.JLabel lbl_TieuDe;
    private javax.swing.JLabel lbl_TongTien;
    private javax.swing.JPanel pnl_DSDichVu;
    private javax.swing.JPanel pnl_DSPhong;
    private javax.swing.JPanel pnl_Phai;
    private javax.swing.JPanel pnl_ThongTinKhachHang;
    private javax.swing.JPanel pnl_ThuTien;
    private javax.swing.JPanel pnl_TienThanhToan;
    private javax.swing.JPanel pnl_Trai;
    private javax.swing.JPanel pnl_Tren;
    private javax.swing.JRadioButton rad_XuatHoaDon;
    private javax.swing.JTable tbl_DSDichVu;
    private javax.swing.JTable tbl_DSPhong;
    private javax.swing.JTextField txt_ChietKhau;
    private javax.swing.JTextField txt_HangThanhVien;
    private javax.swing.JTextField txt_SoDienThoai;
    private javax.swing.JTextField txt_TenKhachHang;
    private javax.swing.JTextField txt_Thue;
    private javax.swing.JTextField txt_TienDichVu;
    private javax.swing.JTextField txt_TienNhan;
    private javax.swing.JTextField txt_TienPhong;
    private javax.swing.JTextField txt_TienThanhToan;
    private javax.swing.JTextField txt_TienThua;
    private javax.swing.JTextField txt_TongTien;
    // End of variables declaration//GEN-END:variables
}
